language: node_js

node_js:
  - '8.9.4'
  
install:
 — npm install phantomjs -g
 — npm install -g mocha-phantomjs
 — npm install -g gulp
 — npm install -g bower
 — npm install
 — bower install
before_script:
 — phantomjs —version
 — mocha-phantomjs —version
 — gulp &
 — sleep 5 # give gulp background task some time to execute.
script:
 — mocha-phantomjs out/test/index.html
 — make test

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn test #caso você tenha algum teste para ser rodado
  - bash ./teste.sh
  - bash ./deploy.sh
